# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './openroad.ui'
#
# Created: Mon Jul 13 17:42:55 2009
#      by: PyQt4 UI code generator 4.5.2-snapshot-20090703
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.settingTab = QtGui.QTabWidget(self.centralwidget)
        self.settingTab.setGeometry(QtCore.QRect(70, 40, 651, 161))
        self.settingTab.setTabPosition(QtGui.QTabWidget.North)
        self.settingTab.setTabShape(QtGui.QTabWidget.Triangular)
        self.settingTab.setObjectName("settingTab")
        self.tabAP = QtGui.QWidget()
        self.tabAP.setObjectName("tabAP")
        self.editAP1 = QtGui.QLineEdit(self.tabAP)
        self.editAP1.setGeometry(QtCore.QRect(300, 20, 113, 22))
        self.editAP1.setObjectName("editAP1")
        self.label_ap1 = QtGui.QLabel(self.tabAP)
        self.label_ap1.setGeometry(QtCore.QRect(260, 23, 31, 17))
        self.label_ap1.setObjectName("label_ap1")
        self.label_ap2 = QtGui.QLabel(self.tabAP)
        self.label_ap2.setGeometry(QtCore.QRect(260, 52, 31, 17))
        self.label_ap2.setObjectName("label_ap2")
        self.editAP2 = QtGui.QLineEdit(self.tabAP)
        self.editAP2.setGeometry(QtCore.QRect(300, 50, 113, 22))
        self.editAP2.setObjectName("editAP2")
        self.label_ap3 = QtGui.QLabel(self.tabAP)
        self.label_ap3.setGeometry(QtCore.QRect(260, 80, 31, 17))
        self.label_ap3.setObjectName("label_ap3")
        self.editAP3 = QtGui.QLineEdit(self.tabAP)
        self.editAP3.setGeometry(QtCore.QRect(300, 79, 113, 22))
        self.editAP3.setObjectName("editAP3")
        self.settingTab.addTab(self.tabAP, "")
        self.tabWiFi = QtGui.QWidget()
        self.tabWiFi.setObjectName("tabWiFi")
        self.label_wifi_if_1 = QtGui.QLabel(self.tabWiFi)
        self.label_wifi_if_1.setGeometry(QtCore.QRect(179, 20, 131, 20))
        self.label_wifi_if_1.setObjectName("label_wifi_if_1")
        self.editWiFiIF1 = QtGui.QLineEdit(self.tabWiFi)
        self.editWiFiIF1.setGeometry(QtCore.QRect(320, 20, 121, 22))
        self.editWiFiIF1.setObjectName("editWiFiIF1")
        self.editWiFiIF2 = QtGui.QLineEdit(self.tabWiFi)
        self.editWiFiIF2.setGeometry(QtCore.QRect(321, 50, 121, 22))
        self.editWiFiIF2.setObjectName("editWiFiIF2")
        self.label_wifi_if_2 = QtGui.QLabel(self.tabWiFi)
        self.label_wifi_if_2.setGeometry(QtCore.QRect(162, 50, 151, 20))
        self.label_wifi_if_2.setObjectName("label_wifi_if_2")
        self.settingTab.addTab(self.tabWiFi, "")
        self.tabBond = QtGui.QWidget()
        self.tabBond.setObjectName("tabBond")
        self.label_bond_ip = QtGui.QLabel(self.tabBond)
        self.label_bond_ip.setGeometry(QtCore.QRect(150, 10, 151, 20))
        self.label_bond_ip.setObjectName("label_bond_ip")
        self.editBondIP = QtGui.QLineEdit(self.tabBond)
        self.editBondIP.setGeometry(QtCore.QRect(310, 10, 121, 22))
        self.editBondIP.setObjectName("editBondIP")
        self.label_bond_mac = QtGui.QLabel(self.tabBond)
        self.label_bond_mac.setGeometry(QtCore.QRect(212, 70, 91, 20))
        self.label_bond_mac.setObjectName("label_bond_mac")
        self.editBondMac = QtGui.QLineEdit(self.tabBond)
        self.editBondMac.setGeometry(QtCore.QRect(310, 70, 121, 22))
        self.editBondMac.setObjectName("editBondMac")
        self.label_bond_if = QtGui.QLabel(self.tabBond)
        self.label_bond_if.setGeometry(QtCore.QRect(199, 100, 101, 20))
        self.label_bond_if.setObjectName("label_bond_if")
        self.editBondMacIF = QtGui.QLineEdit(self.tabBond)
        self.editBondMacIF.setGeometry(QtCore.QRect(310, 100, 121, 22))
        self.editBondMacIF.setObjectName("editBondMacIF")
        self.label_bond_ip_nowimax = QtGui.QLabel(self.tabBond)
        self.label_bond_ip_nowimax.setGeometry(QtCore.QRect(153, 40, 151, 20))
        self.label_bond_ip_nowimax.setObjectName("label_bond_ip_nowimax")
        self.editBondIP_nowimax = QtGui.QLineEdit(self.tabBond)
        self.editBondIP_nowimax.setGeometry(QtCore.QRect(311, 39, 121, 22))
        self.editBondIP_nowimax.setObjectName("editBondIP_nowimax")
        self.settingTab.addTab(self.tabBond, "")
        self.tabWimax = QtGui.QWidget()
        self.tabWimax.setObjectName("tabWimax")
        self.label_wimax_if = QtGui.QLabel(self.tabWimax)
        self.label_wimax_if.setGeometry(QtCore.QRect(150, 22, 151, 20))
        self.label_wimax_if.setObjectName("label_wimax_if")
        self.editWimaxIF = QtGui.QLineEdit(self.tabWimax)
        self.editWimaxIF.setGeometry(QtCore.QRect(310, 20, 113, 22))
        self.editWimaxIF.setObjectName("editWimaxIF")
        self.isUseWiMax = QtGui.QCheckBox(self.tabWimax)
        self.isUseWiMax.setGeometry(QtCore.QRect(290, 60, 101, 21))
        self.isUseWiMax.setChecked(True)
        self.isUseWiMax.setObjectName("isUseWiMax")
        self.settingTab.addTab(self.tabWimax, "")
        self.tabGeneral = QtGui.QWidget()
        self.tabGeneral.setObjectName("tabGeneral")
        self.wifiAssoTimeSpinBox = QtGui.QSpinBox(self.tabGeneral)
        self.wifiAssoTimeSpinBox.setGeometry(QtCore.QRect(320, 20, 91, 21))
        self.wifiAssoTimeSpinBox.setMaximum(100000)
        self.wifiAssoTimeSpinBox.setSingleStep(1000)
        self.wifiAssoTimeSpinBox.setProperty("value", QtCore.QVariant(50000))
        self.wifiAssoTimeSpinBox.setObjectName("wifiAssoTimeSpinBox")
        self.label_WifiAssocTime = QtGui.QLabel(self.tabGeneral)
        self.label_WifiAssocTime.setGeometry(QtCore.QRect(76, 21, 241, 20))
        self.label_WifiAssocTime.setObjectName("label_WifiAssocTime")
        self.label_gw = QtGui.QLabel(self.tabGeneral)
        self.label_gw.setGeometry(QtCore.QRect(253, 50, 61, 20))
        self.label_gw.setObjectName("label_gw")
        self.editGW = QtGui.QLineEdit(self.tabGeneral)
        self.editGW.setGeometry(QtCore.QRect(320, 50, 121, 22))
        self.editGW.setObjectName("editGW")
        self.settingTab.addTab(self.tabGeneral, "")
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(40, 340, 691, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.ButtonRun = QtGui.QPushButton(self.centralwidget)
        self.ButtonRun.setGeometry(QtCore.QRect(360, 210, 113, 32))
        self.ButtonRun.setObjectName("ButtonRun")
        self.label_output = QtGui.QLabel(self.centralwidget)
        self.label_output.setGeometry(QtCore.QRect(360, 360, 111, 20))
        self.label_output.setObjectName("label_output")
        self.label_settings = QtGui.QLabel(self.centralwidget)
        self.label_settings.setGeometry(QtCore.QRect(380, 10, 111, 20))
        self.label_settings.setObjectName("label_settings")
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(40, 240, 691, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_status = QtGui.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(350, 252, 141, 20))
        self.label_status.setObjectName("label_status")
        self.label_wifi_status_1 = QtGui.QLabel(self.centralwidget)
        self.label_wifi_status_1.setGeometry(QtCore.QRect(310, 280, 61, 17))
        self.label_wifi_status_1.setObjectName("label_wifi_status_1")
        self.label_wifi_status_2 = QtGui.QLabel(self.centralwidget)
        self.label_wifi_status_2.setGeometry(QtCore.QRect(310, 300, 61, 17))
        self.label_wifi_status_2.setObjectName("label_wifi_status_2")
        self.label_wimax_status = QtGui.QLabel(self.centralwidget)
        self.label_wimax_status.setGeometry(QtCore.QRect(310, 320, 61, 17))
        self.label_wimax_status.setObjectName("label_wimax_status")
        self.wifi_status_1 = QtGui.QLabel(self.centralwidget)
        self.wifi_status_1.setGeometry(QtCore.QRect(390, 280, 111, 17))
        self.wifi_status_1.setObjectName("wifi_status_1")
        self.wifi_status_2 = QtGui.QLabel(self.centralwidget)
        self.wifi_status_2.setGeometry(QtCore.QRect(390, 300, 121, 17))
        self.wifi_status_2.setObjectName("wifi_status_2")
        self.wimax_status = QtGui.QLabel(self.centralwidget)
        self.wimax_status.setGeometry(QtCore.QRect(390, 321, 131, 17))
        self.wimax_status.setObjectName("wimax_status")
        self.OutputText = QtGui.QPlainTextEdit(self.centralwidget)
        self.OutputText.setGeometry(QtCore.QRect(72, 381, 651, 201))
        self.OutputText.setReadOnly(True)
        self.OutputText.setObjectName("OutputText")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.actionAP_Settings = QtGui.QAction(MainWindow)
        self.actionAP_Settings.setObjectName("actionAP_Settings")
        self.actionWiFi_Interfaces = QtGui.QAction(MainWindow)
        self.actionWiFi_Interfaces.setObjectName("actionWiFi_Interfaces")
        self.actionBonding_Drivers = QtGui.QAction(MainWindow)
        self.actionBonding_Drivers.setObjectName("actionBonding_Drivers")
        self.actionWiMAX = QtGui.QAction(MainWindow)
        self.actionWiMAX.setObjectName("actionWiMAX")
        self.menuSettings.addAction(self.actionAP_Settings)
        self.menuSettings.addAction(self.actionWiFi_Interfaces)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.settingTab.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "OpenRoad Tricast Demo", None, QtGui.QApplication.UnicodeUTF8))
        self.editAP1.setText(QtGui.QApplication.translate("MainWindow", "cleanslatewifi1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ap1.setText(QtGui.QApplication.translate("MainWindow", "AP1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ap2.setText(QtGui.QApplication.translate("MainWindow", "AP2", None, QtGui.QApplication.UnicodeUTF8))
        self.editAP2.setText(QtGui.QApplication.translate("MainWindow", "cleanslatewifi4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ap3.setText(QtGui.QApplication.translate("MainWindow", "AP3", None, QtGui.QApplication.UnicodeUTF8))
        self.editAP3.setText(QtGui.QApplication.translate("MainWindow", "cleanslatewifi3", None, QtGui.QApplication.UnicodeUTF8))
        self.settingTab.setTabText(self.settingTab.indexOf(self.tabAP), QtGui.QApplication.translate("MainWindow", "AP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_wifi_if_1.setText(QtGui.QApplication.translate("MainWindow", "First InterFace Name", None, QtGui.QApplication.UnicodeUTF8))
        self.editWiFiIF1.setText(QtGui.QApplication.translate("MainWindow", "ath1", None, QtGui.QApplication.UnicodeUTF8))
        self.editWiFiIF2.setText(QtGui.QApplication.translate("MainWindow", "wlan0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_wifi_if_2.setText(QtGui.QApplication.translate("MainWindow", "Second InterFace Name", None, QtGui.QApplication.UnicodeUTF8))
        self.settingTab.setTabText(self.settingTab.indexOf(self.tabWiFi), QtGui.QApplication.translate("MainWindow", "WiFi Interface", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bond_ip.setText(QtGui.QApplication.translate("MainWindow", "IP Address with WiMAX", None, QtGui.QApplication.UnicodeUTF8))
        self.editBondIP.setText(QtGui.QApplication.translate("MainWindow", "192.168.2.226", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bond_mac.setText(QtGui.QApplication.translate("MainWindow", "MAC Address ", None, QtGui.QApplication.UnicodeUTF8))
        self.editBondMac.setText(QtGui.QApplication.translate("MainWindow", "00:1c:f0:ee:5a:d1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bond_if.setText(QtGui.QApplication.translate("MainWindow", "InterFace Name", None, QtGui.QApplication.UnicodeUTF8))
        self.editBondMacIF.setText(QtGui.QApplication.translate("MainWindow", "bond0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bond_ip_nowimax.setText(QtGui.QApplication.translate("MainWindow", "IP Address w/o WiMAX", None, QtGui.QApplication.UnicodeUTF8))
        self.editBondIP_nowimax.setText(QtGui.QApplication.translate("MainWindow", "192.168.2.140", None, QtGui.QApplication.UnicodeUTF8))
        self.settingTab.setTabText(self.settingTab.indexOf(self.tabBond), QtGui.QApplication.translate("MainWindow", "Bonding Driver", None, QtGui.QApplication.UnicodeUTF8))
        self.label_wimax_if.setText(QtGui.QApplication.translate("MainWindow", "WiMAX Interface Name", None, QtGui.QApplication.UnicodeUTF8))
        self.editWimaxIF.setText(QtGui.QApplication.translate("MainWindow", "eth1", None, QtGui.QApplication.UnicodeUTF8))
        self.isUseWiMax.setText(QtGui.QApplication.translate("MainWindow", "Use WiMAX", None, QtGui.QApplication.UnicodeUTF8))
        self.settingTab.setTabText(self.settingTab.indexOf(self.tabWimax), QtGui.QApplication.translate("MainWindow", "WiMAX", None, QtGui.QApplication.UnicodeUTF8))
        self.label_WifiAssocTime.setText(QtGui.QApplication.translate("MainWindow", "WiFi Association Time (micro second)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_gw.setText(QtGui.QApplication.translate("MainWindow", "Gateway ", None, QtGui.QApplication.UnicodeUTF8))
        self.editGW.setText(QtGui.QApplication.translate("MainWindow", "192.168.2.254", None, QtGui.QApplication.UnicodeUTF8))
        self.settingTab.setTabText(self.settingTab.indexOf(self.tabGeneral), QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.ButtonRun.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.label_output.setText(QtGui.QApplication.translate("MainWindow", "Output Message", None, QtGui.QApplication.UnicodeUTF8))
        self.label_settings.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_status.setText(QtGui.QApplication.translate("MainWindow", "Association Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_wifi_status_1.setText(QtGui.QApplication.translate("MainWindow", "WiFi #1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_wifi_status_2.setText(QtGui.QApplication.translate("MainWindow", "WiFi #2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_wimax_status.setText(QtGui.QApplication.translate("MainWindow", "WiMax", None, QtGui.QApplication.UnicodeUTF8))
        self.wifi_status_1.setText(QtGui.QApplication.translate("MainWindow", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.wifi_status_2.setText(QtGui.QApplication.translate("MainWindow", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.wimax_status.setText(QtGui.QApplication.translate("MainWindow", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAP_Settings.setText(QtGui.QApplication.translate("MainWindow", "Show Debug Message", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWiFi_Interfaces.setText(QtGui.QApplication.translate("MainWindow", "Show Status", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBonding_Drivers.setText(QtGui.QApplication.translate("MainWindow", "Bonding Driver", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWiMAX.setText(QtGui.QApplication.translate("MainWindow", "WiMAX", None, QtGui.QApplication.UnicodeUTF8))

